# Generated by Django 5.0.3 on 2025-12-07 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SteamUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "steam_id",
                    models.CharField(
                        max_length=17, unique=True, verbose_name="Steam ID"
                    ),
                ),
                (
                    "persona_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя в Steam"
                    ),
                ),
                (
                    "profile_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL профиля"
                    ),
                ),
                (
                    "avatar",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Маленький аватар"
                    ),
                ),
                (
                    "avatar_medium",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Средний аватар"
                    ),
                ),
                (
                    "avatar_full",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Полный аватар"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steam_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Steam пользователь",
                "verbose_name_plural": "Steam пользователи",
            },
        ),
    ]
