# Generated by Django 4.2.7 on 2025-12-08 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('in_trade', 'В обмене'), ('sold', 'Продан')], default='available', max_length=20)),
                ('acquired_date', models.DateTimeField(auto_now_add=True)),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.skin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Скин пользователя',
                'verbose_name_plural': 'Скины пользователей',
                'db_table': 'inventory_userskin',
                'unique_together': {('user', 'skin')},
            },
        ),
    ]
