# Generated by Django 4.2.7 on 2025-12-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('skin_type', models.CharField(max_length=100, verbose_name='Тип')),
                ('rarity', models.CharField(choices=[('common', 'Обычный'), ('uncommon', 'Необычный'), ('rare', 'Редкий'), ('mythical', 'Мифический'), ('legendary', 'Легендарный'), ('ancient', 'Древний'), ('immortal', 'Бессмертный')], max_length=20, verbose_name='Редкость')),
                ('image_url', models.URLField(max_length=500, verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Скин',
                'verbose_name_plural': 'Скины',
                'db_table': 'catalog_skin',
            },
        ),
    ]
