# Generated by Django 6.0 on 2025-12-20 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steam_auth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SteamInventoryCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("steam_id", models.CharField(max_length=20)),
                ("appid", models.CharField(max_length=10)),
                ("contextid", models.CharField(max_length=10)),
                ("items_data", models.JSONField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("total_items", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_cache",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Кэш инвентаря Steam",
                "verbose_name_plural": "Кэши инвентаря Steam",
                "unique_together": {("user", "steam_id", "appid", "contextid")},
            },
        ),
    ]
